### ISSUE TITLE
Wrong handling of empty section in submission.yaml

### ISSUE THREAD

**Issue by michal-szostak** [HEPData/hepdata-validator#1]
Code handling validation of submission.yaml is iterating sections with an assumption that they are dictionaries (or dict like objects)

```
            data = yaml.load_all(open(file_path, 'r'))
            for data_item in data:
                try:
                    if 'comment' in data_item:
                        validate(data_item, additional_file_section_schema)
                    else:
                        validate(data_item, submission_file_schema)
             #.......
```

Which may not always be so - in same cases ```data_item``` may be ```None``` (in case of empty section), and in such an situation generic: ```TypeError: argument of type 'NoneType' is not iterable``` is thrown instead of ValidationError. 

If some sections are always required ( @eamonnmag @jstypka ? Can you confirm? ) just checking for ```None``` and throwing ```ValidationError``` should be enaugh. If main section of the submission.yaml may be empty some additional considerations may be needed.

**Comment by eamonnmag** [comment]
Empty JSON documents are not possible within the spec, but if there is one,
it should be ignored.

**Comment by michal-szostak** [comment]
The changes were pulled, but the PyPI package should also be updated, can you do that @eamonnmag ?

**Comment by eamonnmag** [comment]
Done. Should be available soon.

**Comment by michal-szostak** [comment]
Great, hepdata-converter tests on travis are passing now, I'm closing the issue.
