### ISSUE TITLE
Check that the given schema version is valid on creating the validator

### ISSUE THREAD

**Issue by alisonrclarke** [HEPData/hepdata-validator#12]
Currently there are no checks that the given schema is valid when creating a validator - the validator will crash at the point of validation if the schema is invalid.

I guess we should:
- create a list of valid schemas as a public variable
- check that the schema is one of those values, in addition to checking the file exists, when a validator is initialised

**Comment by alisonrclarke** [comment]
(I realise this bug was introduced in my own changes!)

**Comment by alisonrclarke** [comment]
See comments on #11 as well - it might be worth modifying line 124 of data_file_validator.py.

**Comment by GraemeWatt** [comment]
@alisonrclarke: can you work on this please?

**Comment by alisonrclarke** [comment]
> See comments on #11 as well - it might be worth modifying line 124 of data_file_validator.py.

Actually, once we know the schema version is a member of a defined list I think we can risk the cast to int of the first part - if we ever change the schema numbering format then it's something that will be obvious at that point.
