### ISSUE TITLE
Unify additional_resources between JSON schemas for whole record and tables

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata-validator#23]
The `additional_resources` in `additional_info_schema.json` are defined as:

https://github.com/HEPData/hepdata-validator/blob/31a29e00a71eec31930fa843e20e5958be13c2f1/hepdata_validator/schemas/1.0.1/additional_info_schema.json#L49-L69

while in `submission_schema.json` they are defined as:

https://github.com/HEPData/hepdata-validator/blob/31a29e00a71eec31930fa843e20e5958be13c2f1/hepdata_validator/schemas/1.0.1/submission_schema.json#L41-L63

These two definitions should be unified, i.e.

1.  `submission_schema.json` misses `description` as a `required` property.  This causes the submission code to give an exception if `description` is missing, since the code relies on it:

https://github.com/HEPData/hepdata/blob/4b5c869ca7d9cabacb6b284f7196d0807fb484de/hepdata/modules/records/utils/submission.py#L355

2.  An optional `type` property is allowed in `submission_schema.json` but not in `additional_info_schema.json`.  This is not currently used anywhere, but it should probably be allowed for possible future extensions.

3.  `maxlength` restrictions are imposed in `submission_schema.json` but not in `additional_info_schema.json`.  These restrictions should be imposed in both schema to reflect the database model.

4.  The `"additionalProperties": false` present in `submission_schema.json` should also be applied to `additional_info_schema.json`.

**Comment by alisonrclarke** [comment]
Would it make sense to define `additional_resources` in a separate schema and use [$ref](https://json-schema.org/understanding-json-schema/structuring.html#ref) to include them in `submission_schema` and `additional_info_schema`? Might make it slightly harder for users to understand though, unless we create a bundled version that's public.
