### ISSUE TITLE
Print out key giving ValidationError

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata-validator#28]
The [jsonschema](https://pypi.org/project/jsonschema/) package only prints out the value giving a `ValidationError`, not the associated key.  This is often not informative, for example, if the value is `None`:
```
error - None is not of type 'string' in None
```
arising from a `submission.yaml` file containing:
```yaml
data_license: {description: null, name: null, url: null}
```
This line was originally written by default when converting from the `oldhepdata` format (see HEPData/hepdata-converter#32), therefore many old submissions are now invalidated.  The key giving rise to a `ValidationError` should be printed in addition to the invalid value.  See [Handling Validation Errors](https://python-jsonschema.readthedocs.io/en/stable/errors/#handling-validation-errors) in the `jsonschema` docs.

**Comment by alisonrclarke** [comment]
Pasting the above into one of the test files and stepping through, it looks like the `path` of the `ValidationError` gives us the details we need:

```['data_license', 'name']```

So perhaps we could just add the contents of the path, separated by colons or slashes, to the 'in' part of the message, e.g.

> error - None is not of type 'string' in data_license:name:None

For an invalid keyword this could look something like:

> 'energies' is not one of ['cmenergies', 'observables', 'reactions', 'phrases'] in keywords:2:name:energies

(2 is the index of the item in the list - would we want to modify indices to make them easier to read?)

**Comment by alisonrclarke** [comment]
Draft PR in #31. Sample error messages:

Using a number instead of a string for `data_file`:

```
error - 12321 is not of type 'string' in 'data_file' (expected: {'type': 'string'})
```

Missing license info:

```
error - None is not of type 'string' in 'data_license.name' (expected: {'type': 'string', 'maxLength': 256})
```

Invalid cmenergies value (this had to be fudged slightly as it doesn't come directly from the schema):

```
error - Invalid value (in GeV) for cmenergies: '7000 GeV' in 'keywords[2].name.cmenergies' (expected: {'type': 'number or hyphen-separated range of numbers e.g. 1.7-4.7'})
```

Do these look OK?
