### ISSUE TITLE
Update local pyhf schema to fix test

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata-validator#29]
The commit https://github.com/scikit-hep/pyhf/commit/cbf8d033c2172c3452422719cea51c631af4d6bd by @kratsg breaks a test `testsuite/test_schema_resolver.py::test_json_resolver_existing_schema` written by @Sinclert.  I'll update the local `custom_remote_data_schema.json` file to fix the test.  I'll also introduce nightly CI tests to catch situations like this in future.  (A user reported this issue last Friday.)  I thought that pyhf schema are versioned (e.g. `v1.0.0`) and so should not change, but maybe `v1.0.0` is not yet stable.

**Comment by kratsg** [comment]
The schema is versioned - meaning v1.0.0 should work for all _valid_ HiFa JSON documents. Not that it refers to v1.0.0 of the schema itself. The idea is that schemas evolve in a backwards-compatible fashion. Once we reach a point in which there is a backwards-breaking change, we then must bump the version up. If it helps, treat the schema like an API specification document.

We do a lot of testing to make sure things are backwards-compatible, so this shouldn't catch you by surprise. All you should ensure is that the schema returns the version you expect.
