### ISSUE TITLE
Require both 'low' and 'high' (or neither) values of an independent variable

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata-validator#30]
The current code accepts `low` without `high` values, or `high` without `low` values, meaning that a submission is accepted, but the table fails to render with a JavaScript error `TypeError: undefined is not an object (evaluating 'e[a].replace')` from [this line](https://github.com/HEPData/hepdata/blob/a64ee94f7e47892907e4896de22c23bc92674da6/hepdata/modules/records/assets/js/hepdata_vis_common.js#L353) of the `hepdata_vis_common.js` file in the main web app.  Either `low` *and* `high` values should be present, or neither (in which case a `value` should be present).

**Comment by alisonrclarke** [comment]
Can I check whether we should allow one item with `value` and another with `low` and `high` (as is done in [valid_file.json](https://github.com/HEPData/hepdata-validator/blob/e6c3507130b103a99413b12cd262b6f2d9b3059a/testsuite/test_data/valid_file.json#L8) in the tests), or should all the items be consistent?

**Comment by GraemeWatt** [comment]
> Can I check whether we should allow one item with `value` and another with `low` and `high` (as is done in [valid_file.json](https://github.com/HEPData/hepdata-validator/blob/e6c3507130b103a99413b12cd262b6f2d9b3059a/testsuite/test_data/valid_file.json#L8) in the tests), or should all the items be consistent?

A mixture is allowed, so each item of `values` can be validated independently.
