### ISSUE TITLE
Update additional_info_schema

### ISSUE THREAD

**Issue by alisonrclarke** [HEPData/hepdata-validator#35]
From discussion on #34:

> Most of the properties in `additional_info_schema.json` were used for migration from the old hepdata.cedar.ac.uk site and should not be present for new submissions. New submissions should only contain comment and additional_resources, but neither is required. Conversion from the oldhepdata format also writes `record_ids`, although they are not used anywhere. We should also allow an optional `hepdata_doi` similar to the `table_doi` in `submission_schema.json` so that YAML downloads from hepdata.net can be uploaded and pass validation. So I think we could just keep these four properties (`comment`, `additional_resources`, `record_ids`, `hepdata_doi`) and set `"additionalProperties": false`, but we'd need to check whether this breaks anything and the test data might need to be updated.

**Comment by GraemeWatt** [comment]
We decided it's simpler to leave `additional_info_schema.json` alone to avoid breaking existing submissions with the extra fields, so I'm closing this issue.
