### ISSUE TITLE
Split badges in README to have render better on GitHub

### ISSUE THREAD

**Issue by matthewfeickert** [HEPData/hepdata-validator#60]
GitHub has changed some of the ways that they render files in the last months, and one of those changes means that if badges are displayed in a `.rst` file like they are in the README now

https://github.com/HEPData/hepdata-validator/blob/bfcd4fd2c3bec027816944a60ca92a270e1c356b/README.rst?plain=1#L5-L31

they will be too much for a single line and GitHub will instead decide to display each one on its own line, which isn't great.

To get around this, myself and others (c.f. https://github.com/TDAmeritrade/stumpy/commit/86d70158561c3774661f23ef2ac1a330dafd7511) have noticed that if a 

```rst
|PyPI Version| 

.. |PyPI Version| image:: https://img.shields.io/pypi/v/hepdata-validator 
   :target: https://pypi.org/project/hepdata-validator/ 
   :alt: PyPI Version 
```

format is used then things render as intended.

**Comment by GraemeWatt** [comment]
@matthewfeickert : thanks for the tip!  I had noticed the change in the display of the badges, but I hadn't investigated how to fix it.  Now addressed by PR #61.
