### ISSUE TITLE
Select testing framework

### ISSUE THREAD

**Issue by Sinclert** [HEPData/hepdata-validator#8]
I am looking into this repository, as it was mentioned in [this HEP-Data issue](https://github.com/HEPData/hepdata/issues/164#issuecomment-588257204), and I see that there are 2 testing frameworks defined: `unittest` and `pytest`.

- `unittest` is present on the tests definitions. Example:

    ```python
        class SubmissionFileValidationTest(unittest.TestCase):
            ...
     ```
- `pytests` is present on the project dependencies and... `setup.py`? 🤷🏻‍♂️

Right now, both execution works:
```python
pytests testsuite
```

```python
python -m unittest testsuite/validation_test.py
```

However, I find it confusing, and I think that the original idea was to use `pytest`, but at some point in time some initial _"setUp"_ steps were needed before some tests. That may be when the `unittest` syntax was introduced.

Could you decide on a given framework?

I would suggest choosing `pytest`, and replace `unittest` syntax by [pytest fixtures](https://docs.pytest.org/en/latest/fixture.html#fixtures-as-function-arguments). I can create a proposed PR if agreed.

**Comment by GraemeWatt** [comment]
Looking at the history of this repository, the first [commit](https://github.com/HEPData/hepdata-validator/tree/3e6d5d1593701d84c435811a7c14309018a6d0f9) uses only `unittest` and `pytest` was introduced later in the second commit (https://github.com/HEPData/hepdata-validator/commit/0ed211c20d182ca8f07800bd73f93ad098ca3dd8).  A [comment](https://github.com/HEPData/hepdata-converter/pull/24#issuecomment-216125908) by the original developer indicates that both `unittest` and `pytest` were used in the early stages of the project.  The [hepdata](https://github.com/HEPData/hepdata) repository for the main web app uses only `pytest` (including fixtures).  The `.travis.yml` file for this [hepdata-validator](https://github.com/HEPData/hepdata-validator) repository runs `pytest testsuite`.  I agree that it would be good to move to `pytest` everywhere as a Python testing framework and a PR would be very helpful if you're prepared to do the work.  Note that the [hepdata-validator](https://github.com/HEPData/hepdata-validator) code should be compatible with both Python 2 and Python 3 (both are tested in the `.travis.yml` file).

**Comment by Sinclert** [comment]
PR addressing the migration: https://github.com/HEPData/hepdata-validator/pull/10
